import Head from 'next/head'
import Image from 'next/image'
import Resume from "../src/settings/resume.json"

export default function Home() {
  return (
    <div className={"w-full p-8"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"w-full min-h-[100vh] flex flex-col justify-center items-center text-center"}>
        <h1 className={"text-3xl font-bold text-primary"}>
          Hello {Resume.basics.name}! <br />Welcome to <a href="https://nextjs.org" className='hover:text-secondary'>Next.js!</a>
        </h1>

        <p className={"text-lg"}>
          Get started by editing{' '}
          <code className={"p-1 bg-slate-200 rounded-md"}>pages/index.js</code>
        </p>

        <div className={"flex justify-center items-center flex-wrap max-w-[800px]"}>
          <a href="https://nextjs.org/docs" className={"m-4 p-6 text-left border-2 border-white rounded-xl max-w-[300px] transition-colors hover:text-primary hover:border-primary"}>
            <h2 className={"text-lg mb-1"}>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={"m-4 p-6 text-left border-2 border-white rounded-xl max-w-[300px] transition-colors hover:text-primary hover:border-primary"}>
            <h2 className={"text-lg mb-1"}>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={"m-4 p-6 text-left border-2 border-white rounded-xl max-w-[300px] transition-colors hover:text-primary hover:border-primary"}
          >
            <h2 className={"text-lg mb-1"}>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={"m-4 p-6 text-left border-2 border-white rounded-xl max-w-[300px] transition-colors hover:text-primary hover:border-primary"}
          >
            <h2 className={"text-lg mb-1"}>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={"flex px-4 border-t-white border-t-2 justify-center items-center"}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={"h-4 ml-2"}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
